name: plethodon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas>=2.0
  - geopandas>=0.14
  - pyarrow
  - h3-py>=4.0
  - scipy
  - numpy
  - matplotlib
  - seaborn
  - scikit-image
  - opencv
  - statsmodels
  - pillow
  - requests
  - tqdm
  - shapely
  - pip
  - pip:
    - pyinaturalist>=0.19
